version: 2

jobs:
  build:
    docker:
      - image: 'circleci/node:8.12-browsers'
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: v1-npm-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - run: npm run build

  deploy_production:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: 
          name: Deploy to DigitalOcean
          command: |
            ssh fbb@flexboxbuilder.com "cd ~/flexboxbuilder.com && ./deploy.sh"
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master